name: Deploy iOS to TestFlight

on:
  push:
    branches: [ main ]
    paths:
      - 'builds/ios/Waypoint.ipa'  # Only run when the IPA is updated
  workflow_dispatch:  # Allow manual triggering

jobs:
  deploy:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          lfs: true  # In case the IPA is tracked with Git LFS
      
      - name: Verify IPA exists
        run: |
          if [ -f "builds/ios/Waypoint.ipa" ]; then
            echo "IPA file found. Size: $(du -h builds/ios/Waypoint.ipa | cut -f1)"
          else
            echo "Error: IPA file not found at builds/ios/Waypoint.ipa"
            exit 1
          fi
      
      - name: Upload app to TestFlight
        env:
          APPLE_ID_USERNAME: ${{ secrets.APPLE_ID_USERNAME }}
          APPLE_ID_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_ID_APP_SPECIFIC_PASSWORD }}
        run: |
          xcrun altool --upload-app -f builds/ios/Waypoint.ipa -t ios -u "$APPLE_ID_USERNAME" -p "$APPLE_ID_APP_SPECIFIC_PASSWORD"